Blog/urls.py
from django.conf.urls import url,include
from Blog import views

app_name = 'Blog'
urlpatterns = [
    url(r'^index$', views.index, name='index'),
    url(r'^detail/(?P<id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^archives/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$', views.archives, name='archives'),
    url(r'^category/(?P<id>[0-9]+)/$', views.category, name='category'),
    url(r'^tag/(?P<id>[0-9]+)/$', views.tags, name='tag'),

]

Myite/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include


urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^ljhblog/',include(('Blog.urls', 'Blog'), namespace='Blog')),
    url(r'^ljhblog/',include(('comments.urls', 'comments'), namespace='comments')),
    url(r'^search/', include('haystack.urls')),
]

comments/urls.py
from django.conf.urls import url

from comments import views

app_name = 'comments'
urlpatterns = [
    url(r'^comment/blog/(?P<post_id>[0-9]+)/$', views.blog_comment, name='blog_comment'),
]

Blog/models.py
from django.db import models
from django.urls import reverse
import  markdown
from django.utils.html import strip_tags


class Category(models.Model):
    """博客分类"""
    name = models.CharField(max_length=100)
    class Meta:
        db_table = 'category'
        verbose_name = '博客分类'
        verbose_name_plural = verbose_name
    def __str__(self):
        return self.name

class Tag(models.Model):
    """博客标签"""
    name = models.CharField(max_length=100)
    class Meta:
        db_table = 'tag'
        verbose_name = '博客标签'
        verbose_name_plural = verbose_name
    def __str__(self):
        return self.name

class BlogPost(models.Model):
    """自定义文章类：标题，正文，创建时间，修改时间，摘要，分类，标签，阅读量【再加一个评论？】"""
    title = models.CharField(max_length=100)
    author=models.CharField('作者',max_length=16)
    body = models.TextField()
    created_time = models.DateTimeField()
    modified_time = models.DateTimeField()
    excerpt = models.CharField(max_length=200, blank=True)  # 文章摘要，可为空
    category = models.ForeignKey(Category, on_delete=True)  # ForeignKey表示1对多（多个博文对应1个category）
    tags = models.ManyToManyField(Tag, blank=True)  # 多个博文对应多个标签
    views = models.PositiveIntegerField(default=0)  # 阅读量
    class Meta:
        ordering = ['-created_time']  # 在定义模型类的时候就将博客文章默认按照发布时间的逆序排列，需要说明的是ordering
                                    # 可以跟多个参数，表示的意思是如果按照第一个参数排序结果是一样的话就按照第二个参数排列
        db_table = 'blogpost'
        verbose_name = '博客文章'
        verbose_name_plural = verbose_name
    def __str__(self):
        return self.title

    def increase_views(self):
        '''真实记录博客的阅读量'''
        self.views += 1
        self.save(update_fields=['views'])

    def save(self, *args, **kwargs):
        '''自动生成文章摘要'''
        if not self.excerpt:
            md = markdown.Markdown(extensions=[
                'markdown.extensions.extra',
                'markdown.extensions.codehilite',
            ])
            # 先将 Markdown 文本渲染成 HTML 文本
            # strip_tags 去掉 HTML 文本的全部 HTML 标签
            # 从文本摘取前 54 个字符赋给 excerpt
            self.excerpt = strip_tags(md.convert(self.body))[:54]

        # 调用父类的 save 方法将数据保存到数据库中
        super(BlogPost, self).save(*args, **kwargs)

    # 自定义 get_absolute_url 方法
    # 记得从 django.urls 中导入 reverse 函数
    def get_absolute_url(self):
        return reverse('Blog:detail', kwargs={'id': self.id})





'''
一、数据库的构建(M） 
首先，分析一个博客系统的功能： 
（1）一个博客可以有多个标签（多对多） 
（2）一个博客可以有多条评论(一对多） 
（3）一个博客只可以有一个类别（多对一） 
接下来，分析关系的属性： 
博客：标题，作者，内容，发布时间，分类（外键），标签（多对多）等 
标签：标签名 
类别：分类名 
评论：作者，博客（外键），邮箱，内容，发布时间等。
--------------------- 
原文：https://blog.csdn.net/a18852867035/article/details/66475879 
'''

comments/models.py
from django.db import models
from django.utils.six import python_2_unicode_compatible

# python_2_unicode_compatible 装饰器用于兼容 Python2
@python_2_unicode_compatible
class Comment(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField(max_length=255)
    url = models.URLField(blank=True)
    text = models.TextField()
    created_time = models.DateTimeField(auto_now_add=True)

    post = models.ForeignKey('Blog.BlogPost', on_delete=True)

    class Meta:
        db_table = 'comment'
        verbose_name = '博客评论'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.text[:20]

comments/forms.py
from django import forms
from comments.models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment  # 表明这个表单对应的数据库模型是 Comment 类
        fields = ['name', 'email', 'url', 'text']  # 指定了表单需要显示的字段

Blog/views.py
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator
from Blog.models import BlogPost,Category,Tag
from django.http import Http404
import markdown
from markdown.extensions.toc import TocExtension
from django.utils.text import slugify
from comments.forms import CommentForm
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger  # 内置分页模块
from django.db.models import Q  # Q 对象用于包装查询表达式，其作用是为了提供复杂的查询逻辑。
# 进行归类整理的时候，在主页index和详情页detail中标题下的分类、发布时间、【作者、评论量、阅读量】进行URL指向，【】内的没有完成，有待完善，创建新的视图函数和分类函数

def index(request):
    '''显示首页'''
    post_list = BlogPost.objects.all().order_by('-created_time')
    p = Paginator(post_list, 2)  # 每一页的容量为2
    page = request.GET.get('page')
    try:
        pageshow = p.page(page)
    except PageNotAnInteger:
        # 如果用户请求的页码号不是整数，显示第一页
        pageshow = p.page(1)
    except EmptyPage:
        # 如果用户请求的页码号超过了最大页码号，显示最后一页
        pageshow = p.page(p.num_pages)

    context ={
        'post_list':post_list,
        'pageshow':pageshow
    }
    return render(request,'index.html',context)


def detail(request,id):
    post = get_object_or_404(BlogPost,id=id)
    post.increase_views()  # 阅读量+1
    md = markdown.Markdown(extensions=[
        'markdown.extensions.extra',  # 提供很多扩展
        'markdown.extensions.codehilite',  # 语法高亮扩展
        TocExtension(slugify=slugify), # 自动生成目录
    ])
    post.body = md.convert(post.body)
    post.toc = md.toc
    form = CommentForm()
    comment_list = post.comment_set.all()  # 获取当前博客的所有评论数据
    context = {
        'post': post,
        'form':form,
        'comment_list':comment_list
    }
    return render(request,'detail.html',context)


def archives(request, year, month):
    '''归档视图函数，按照归档日期显示该归档下的所有博客文章'''
    post_list = BlogPost.objects.filter(created_time__year=year,created_time__month=month).order_by('-created_time')
    context = {
        'post_list': post_list
    }
    print(post_list)
    return render(request, 'index.html', context)


def category(request, id):
    '''分类视图函数，根据ID参数查找对应的分类属性，根据分类属性查找所有的博客'''
    cate = get_object_or_404(Category, id=id)
    post_list = BlogPost.objects.filter(category=cate).order_by('-created_time')
    return render(request, 'index.html', context={'post_list': post_list})


def tags(request, id):
    '''标签云视图函数，根据ID参数查找对应的标签属性，根据标签属性查找所有的博客'''
    tag = get_object_or_404(Tag, id=id)
    tag_list = BlogPost.objects.filter(tags=tag).order_by('-created_time')
    return render(request, 'index.html', context={'post_list': tag_list})

comments/views.py
from django.shortcuts import render, get_object_or_404, redirect
from Blog.models import BlogPost

from .models import Comment
from comments.forms import CommentForm


# 注意：从URL获取的参数，不要随便瞎改，直接使用URL传过来的参数变量就好
def blog_comment(request, post_id):
    post = get_object_or_404(BlogPost, id=post_id)  # 先获取被评论的文章，因为后面需要把评论和被评论的文章关联起来。
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)  # commit=False 利用表单的数据生成 Comment 模型类的实例，但还不保存评论数据到数据库。
            comment.post = post  # 将评论和被评论的文章关联起来。
            comment.save()  # 最终将评论数据保存进数据库，调用模型实例的 save 方法

            # 重定向到 post 的详情页，实际上当 redirect 函数接收一个模型的实例时，它会调用这个模型实例的 get_absolute_url 方法，
            # 然后重定向到 get_absolute_url 方法返回的 URL。
            return redirect(post)  # ???是不是可以改成'Blog:detail'，未成功
        else:
            # 检查到数据不合法，重新渲染详情页，并且渲染表单的错误。
            # 因此我们传了三个模板变量给 detail.html，
            # 一个是文章（Post），一个是评论列表，一个是表单 form
            comment_list = post.comment_set.all()
            context = {'post': post,
                       'form': form,
                       'comment_list': comment_list
                       }
            return render(request, 'detail.html', context=context)
    # 不是 post 请求，说明用户没有提交数据，重定向到文章详情页。
    return redirect(post)


'''
下面是作者对上面的 post.comment_set.all()作出的解析：
    post.comment_set.all() 也等价于 Comment.objects.filter(post=post)，即根据 post 来过滤该 post 下的全部评论。
    但既然我们已经有了一个 Post 模型的实例 post（它对应的是 Post 在数据库中的一条记录），那么获取和 post 关联的评论
    列表有一个简单方法，即调用它的 xxx_set 属性来获取一个类似于 objects 的模型管理器，然后调用其 all 方法来返回这个 post 关联
    的全部评论。 其中 xxx_set 中的 xxx 为关联模型的类名（小写）。
    例如 获取cate分类下的所有博客：Post.objects.filter(category=cate) 也可以等价写为 cate.post_set.all()。

'''

templates/base.html
{% load staticfiles %}
{% load blog_tags %}
<!DOCTYPE html>
<html>
<head>
    <title>我的博客</title>
    <style>
        span.highlighted{
            color: red;
        }
    </style>
    <!-- meta -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- css -->
    <link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="{% static 'Blog/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'Blog/css/pace.css' %}">
    <link rel="stylesheet" href="{% static 'Blog/css/custom.css' %}">
    <link rel="stylesheet" href="{% static 'Blog/css/highlights/github.css' %}">

    <style>
        span.highlighted {
            color: red;
        }
    </style>

    <!-- js -->
    <script src="{% static 'Blog/js/jquery-2.1.3.min.js' %}"></script>
    <script src="{% static 'Blog/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'Blog/js/pace.min.js' %}"></script>
    <script src="{% static 'Blog/js/modernizr.custom.js' %}"></script>
</head>

<body>
<div class="container">
    <header id="site-header">
        <div class="row">
            <div class="col-md-4 col-sm-5 col-xs-8">
                <div class="logo">
                    <h1><a href="{% url 'Blog:index' %}"><b>MY</b> &amp; SN</a></h1>
                </div>
            </div><!-- col-md-4 -->
            <div class="col-md-8 col-sm-7 col-xs-4">
                <nav class="main-nav" role="navigation">
                    <div class="navbar-header">
                        <button type="button" id="trigger-overlay" class="navbar-toggle">
                            <span class="ion-navicon"></span>
                        </button>
                    </div>

                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav navbar-right">
                            <li class="cl-effect-11"><a href="{% url 'Blog:index' %}" data-hover="首页">首页</a></li>
                            <li class="cl-effect-11"><a href="#" data-hover="博客">博客</a></li>
                            <li class="cl-effect-11"><a href="#" data-hover="关于">关于</a></li>
                            <li class="cl-effect-11"><a href="#" data-hover="联系">联系</a></li>
                        </ul>
                    </div><!-- /.navbar-collapse -->
                </nav>
                <div id="header-search-box">
                    <a id="search-menu" href="#"><span id="search-icon" class="ion-ios-search-strong"></span></a>
                    <div id="search-form" class="search-form">
                        <form role="search" method="get" id="searchform" action="{% url 'haystack_search' %}">
                            <input type="search" name="q" placeholder="搜索" required>
                            <button type="submit"><span class="ion-ios-search-strong"></span></button>
                        </form>
                    </div>
                </div>
            </div><!-- col-md-8 -->
        </div>
    </header>
</div>
<div class="copyrights">Collect from <a href="http://www.cssmoban.com/">网页模板</a></div>
<div class="copyrights">Modified by <a href="http://zmrenwu.com/">追梦人物的博客</a></div>

<div class="content-body">
    <div class="container">
        <div class="row">
            <main class="col-md-8">
                {% block main %}
                {% endblock main %}
            </main>
            <aside class="col-md-4">
                {% block toc %}
                {% endblock toc %}
                <div class="widget widget-recent-posts">
                    <h3 class="widget-title">最新文章</h3>
                    {% get_recent_posts as recent_post_list %}
                    <ul>
                        {% for post in recent_post_list %}
                            <li>
                                <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                            </li>
                        {% empty %}
                            暂无文章！
                        {% endfor %}
                    </ul>
                </div>
                <div class="widget widget-archives">
                    <h3 class="widget-title">时间归档</h3>
                    {% archives as date_list %}
                    <ul>
                        {% for date in date_list %}
                            <li>
                                <a href="{% url 'Blog:archives' date.year date.month %}">
                                    {{ date.year }} 年 {{ date.month }} 月</a>
                            </li>
                        {% empty %}
                            暂无归档！
                        {% endfor %}
                    </ul>
                </div>

                <div class="widget widget-category">
                    <h3 class="widget-title">分类</h3>
                    {% get_categories as category_list %}
                    <ul>
                        {% for category in category_list %}
                            <li>
                                <a href="{% url 'Blog:category' category.id %}">
                                    {{ category.name }} <span class="post-count">{{ category.num_posts }}</span></a>
                            </li>
                        {% empty %}
                            暂无分类！
                        {% endfor %}
                    </ul>
                </div>

                <div class="widget widget-tag-cloud">
                    <h3 class="widget-title">标签云</h3>
                    {% get_tags as tag_list %}
                    <ul>
                        {% for tag in tag_list %}
                            <li>
                                <a href="{% url 'Blog:tag' tag.id %}">{{ tag.name }}{{ tag.num_posts }}</a>
                            </li>
                        {% empty %}
                            暂无标签！
                        {% endfor %}
                    </ul>
                </div>

                <div class="rss">
                    <a href="#"><span class="ion-social-rss-outline"></span> RSS 订阅</a>
                </div>
            </aside>
        </div>
    </div>
</div>
<footer id="site-footer">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <p class="copyright">&copy 2019 - 采集自<a href="http://www.cssmoban.com/"
                                                        target="_blank" title="模板之家">模板之家</a>
                    - 由<a href="http://zmrenwu.com/" title="网页模板" target="_blank">追梦人物的博客</a>修改
                </p>
            </div>
        </div>
    </div>
</footer>

<!-- Mobile Menu -->
<div class="overlay overlay-hugeinc">
    <button type="button" class="overlay-close"><span class="ion-ios-close-empty"></span></button>
    <nav>
        <ul>
            <li><a href="{% url 'Blog:index' %}">首页</a></li>
            <li><a href="#">博客</a></li>
            <li><a href="#">关于</a></li>
            <li><a href="#">联系</a></li>
        </ul>
    </nav>
</div>

<script src="{% static 'Blog/js/script.js' %}"></script>

</body>
</html>

templates/detail.html
{% extends 'base.html' %}
{% block main %}
    <article class="post post-{{ post.id }}">
        <header class="entry-header">
            <h1 class="entry-title">{{ post.title }}</h1>
            <div class="entry-meta">
                <span class="post-category">
                    <a href="{% url 'Blog:category' post.category.id %}">{{ post.category.name }}</a></span>
                <span class="post-date"><a href="{% url 'Blog:archives' post.created_time.year post.created_time.month %}"><time class="entry-date"
                                                          datetime="{{ post.created_time }}">{{ post.created_time }}</time></a></span>
                <span class="post-author"><a href="#">{{ post.author }}</a></span>
                <span class="comments-link">
                    <a href="{{ post.get_absolute_url }}#comment-area">{{ post.comment_set.count }} 评论</a></span>
                <span class="views-count"><a href="#">{{ post.views }} 阅读</a></span>
            </div>
        </header>
        <div class="entry-content clearfix">
            {{ post.body|safe }}
            <div class="widget-tag-cloud">
                <ul>
                    标签：
                    {% for tag in post.tags.all %}
                        <li><a href="{% url 'Blog:tag' tag.id %}"># {{ tag.name }}</a></li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </article>
    <section class="comment-area" id="comment-area">
        <hr>
        <h3>发表评论</h3>
        <form action="{% url 'comments:blog_comment' post.id %}" method="post" class="comment-form">
            {% csrf_token %}
            <div class="row">
                <div class="col-md-4">
                    <label for="{{ form.name.id_for_label }}">名字：</label>
                    {{ form.name }}
                    {{ form.name.errors }}
                </div>
                <div class="col-md-4">
                    <label for="{{ form.email.id_for_label }}">邮箱：</label>
                    {{ form.email }}
                    {{ form.email.errors }}
                </div>
                <div class="col-md-4">
                    <label for="{{ form.url.id_for_label }}">URL：</label>
                    {{ form.url }}
                    {{ form.url.errors }}
                </div>
                <div class="col-md-12">
                    <label for="{{ form.text.id_for_label }}">评论：</label>
                    {{ form.text }}
                    {{ form.text.errors }}
                    <button type="submit" class="comment-btn">发表</button>
                </div>
            </div>    <!-- row -->
        </form>
        <div class="comment-list-panel">
            <h3>评论列表，共 <span>{{ post.comment_set.count }}</span> 条评论</h3>
            <ul class="comment-list list-unstyled">
                {% for comment in comment_list %}
                    <li class="comment-item">
                        <span class="nickname">{{ comment.name }}</span>
                        <time class="submit-date"
                              datetime="{{ comment.created_time }}">{{ comment.created_time }}</time>
                        <div class="text">
                            {{ comment.text }}
                        </div>
                    </li>
                {% empty %}
                    暂无评论
                {% endfor %}
            </ul>
        </div>
    </section>
{% endblock main %}
{% block toc %}
    <div class="widget widget-content">
        <h3 class="widget-title">文章目录</h3>
        {{ post.toc|safe }}
    </div>
{% endblock toc %}

templates/index.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block main %}
    {% if error_msg %}
        <p>{{ error_msg }}</p>
    {% endif %}
    {% for post in post_list %}
        <article class="post post-{{ post.id }}">
            <header class="entry-header">
                <h1 class="entry-title">
                    <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                </h1>
                <div class="entry-meta">
                    <span class="post-category">
                        <a href="{% url 'Blog:category' post.category.id %}">{{ post.category.name }}</a></span>
                    <span class="post-date"><a href="{% url 'Blog:archives' post.created_time.year post.created_time.month %}"><time class="entry-date"
                                                              datetime="{{ post.created_time }}">
                        {{ post.created_time }}</time></a></span>
                    <span class="post-author"><a href="#">{{ post.author }}</a></span>
                    <span class="comments-link"><a href="#">{{ post.comment_set.count }}</a></span>
                    <span class="views-count"><a href="#">{{ post.views }}</a></span>
                </div>
            </header>
            <div class="entry-content clearfix">
                <p>{{ post.excerpt }}</p>
                <div class="read-more cl-effect-14">
                    <a href="{% url 'Blog:detail' post.id %}" class="more-link">继续阅读 <span class="meta-nav">→</span></a>
                </div>
            </div>
        </article>
    {% empty %}
        <div class="no-post">暂时还没有发布的文章！</div>
    {% endfor %}
    <!-- 简单分页效果
    <div class="pagination-simple">
        <a href="#">上一页</a>
        <span class="current">第 6 页 / 共 11 页</span>
        <a href="#">下一页</a>
    </div>
    -->
    <div class="pagination">
        <!-- 如果当前页还有上一页，显示一个上一页的按钮 -->
      {% if pageshow.has_previous %}
        <a href="?page={{ pageshow.previous_page_number }}">上一页</a>
      {% endif %}
      <!-- 显示当前页面信息 -->
      <span class="current">第 {{ pageshow.number }} 页 / 共 {{ pageshow.num_pages }} 页</span>
      <!-- 如果当前页还有下一页，显示一个下一页的按钮 -->
      {% if pageshow.has_next %}
        <a href="?page={{ pageshow.next_page_number }}">下一页</a>
      {% endif %}
    </div>
{% endblock main %}
<footer id="site-footer">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <p class="copyright">&copy 2019 - 采集自<a href="http://www.cssmoban.com/"
                                                        target="_blank" title="模板之家">模板之家</a>
                    - 由<a href="http://zmrenwu.com/" title="网页模板" target="_blank">追梦人物的博客</a>修改
                </p>
            </div>
        </div>
    </div>
</footer>

<!-- Mobile Menu -->
<div class="overlay overlay-hugeinc">
    <button type="button" class="overlay-close"><span class="ion-ios-close-empty"></span></button>
    <nav>
        <ul>
            <li><a href="index.html">首页</a></li>
            <li><a href="full-width.html">博客</a></li>
            <li><a href="about.html">关于</a></li>
            <li><a href="contact.html">联系</a></li>
        </ul>
    </nav>
</div>

<script src="{% static 'Blog/js/script.js' %}"></script>

templates/search/search.html
{% extends 'base.html' %}
{% load highlight %}

{% block main %}
    {% if query %}
        {% for result in page.object_list %}
            <article class="post post-{{ result.object.id }}">
                <header class="entry-header">
                    <h1 class="entry-title">
                        <a href="{{ result.object.get_absolute_url }}">{% highlight result.object.title with query %}</a>
                    </h1>
                    <div class="entry-meta">
                    <span class="post-category">
                        <a href="{% url 'Blog:category' result.object.category.id %}">
                            {{ result.object.category.name }}</a></span>
                        <span class="post-date"><a href="#">
                            <time class="entry-date" datetime="{{ result.object.created_time }}">
                                {{ result.object.created_time }}</time></a></span>
                        <span class="post-author"><a href="#">{{ result.object.author }}</a></span>
                        <span class="comments-link">
                        <a href="{{ result.object.get_absolute_url }}#comment-area">
                            {{ result.object.comment_set.count }} 评论</a></span>
                        <span class="views-count"><a
                                href="{{ result.object.get_absolute_url }}">{{ result.object.views }} 阅读</a></span>
                    </div>
                </header>
                <div class="entry-content clearfix">
                    <p>{% highlight result.object.body with query %}</p>
                    <div class="read-more cl-effect-14">
                        <a href="{{ result.object.get_absolute_url }}" class="more-link">继续阅读 <span
                                class="meta-nav">→</span></a>
                    </div>
                </div>
            </article>
        {% empty %}
            <div class="no-post">没有搜索到你想要的结果！</div>
        {% endfor %}
        {% if page.has_previous or page.has_next %}
            <div>
                {% if page.has_previous %}
                    <a href="?q={{ query }}&amp;page={{ page.previous_page_number }}">{% endif %}&laquo; Previous
                {% if page.has_previous %}</a>{% endif %}
                |
                {% if page.has_next %}<a href="?q={{ query }}&amp;page={{ page.next_page_number }}">{% endif %}Next
                &raquo;{% if page.has_next %}</a>{% endif %}
            </div>
        {% endif %}
    {% else %}
        请输入搜索关键词，例如 django
    {% endif %}
{% endblock main %}